all:exercicis

exercicis:triangle.cc retallat.cc trimou.cc

	g++ triangle.cc -o triangle.x -lGL -lglut
	g++ retallat.cc -o retallat.x -lGL -lglut
	g++ trimou.cc -o trimou.x -lGL -lglut

clean:
	rm -f exercicis
